apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ibmcloud-template
spec:
  params:
    - name: message
      description: The message to print
      default: This is the default message
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: ibmcloud-
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        pipelineRef:
            name: ibmcloud-pipeline
        params:
        - name: message
          value: $(params.message)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: ibmcloud-binding
spec:
  params:
    - name: message
      value: binding message
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ibmcloud-listener
spec:
  triggers:
    - binding:
        name: ibmcloud-binding
      template:
        name: ibmcloud-template
      params:
        - name: message-l
          value: Hello from the Manual Triggers EventListener!