apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: ibmcloud-task
spec:
  steps:
    - name: echo
      image: ibmcom/ibm-cloud-developer-tools-amd64
      command: ["/bin/sh", "-c"]
      args:
        - echo starting;
          ls -la;
          git clone https://github.com/skaegi/tekton-example;
          ls -la;
          kubectl get serviceaccounts;
          kubectl get serviceaccount default -o yaml;
          kubectl get ns;
          kubectl get pods;
          kubectl get pods -ntekton-pipelines;
      
