apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: bash-pipeline
spec:
  params:
    - name: message
      default: default pipeline message
  tasks:
    - name: bash-with-a-task
      taskRef:
        name: bash-task
