apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: bash-task
spec:
  steps:
    - name: echo
      image: ubuntu
      command: ["/bin/sh", "-c"]
      args:
        - echo starting;
          ls -la;
      
