apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: shell-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: message
      description: The message to print
      default: This is the default message
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: public-github-repo
      spec:
        type: git
        params:
          - name: url
            value: https://github.com/open-toolchain/hello-containers
          - name: revision
            value: master
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: shell-
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        pipelineRef:
            name: shell-pipeline
        params:
        - name: message
          value: $(params.message)
        resources:
        - name: source-repo
          resourceRef:
            name: public-github-repo
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: shell-binding
spec:
  params:
    - name: message
      value: binding message
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: shell-listener
spec:
  triggers:
    - binding:
        name: shell-binding
      template:
        name: shell-template
      params:
        - name: message-l
          value: Hello from the Manual Triggers EventListener!