apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: shell-task
spec:
  inputs:
    resources:
      - name: workspace
        type: git
        targetPath: .
  steps:
    - name: pre-check
      image: ibmcom/ibm-cloud-developer-tools-amd64
      env:
      - name: APIKEY
        valueFrom:
          secretKeyRef:
            name: ibmcloud-creds
            key: apikey
      command: ["/bin/sh", "-c"]
      args:
        - echo hi;
          ibmcloud config --check-version=false;
          ibmcloud login --apikey $APIKEY --no-region;
          ibmcloud plugin install container-registry;
          source pre-build-check.sh
      
