apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: buildkit-pipeline
spec:
  params:
    - name: message
      default: default pipeline message
  tasks:
    - name: buildkit-with-a-task
      taskRef:
        name: buildkit-task
