apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: buildkit-task
spec:
  steps:
    - name: echo
      image: ibmcom/ibm-cloud-developer-tools-amd64
      command: ["/bin/sh", "-c"]
      args:
        - echo starting;
          kubectl get all;
