apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: shell-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: message
      description: The message to print
      default: This is the default message
  resourcetemplates:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: github-token
        annotations:
          tekton.dev/git-0: https://github.com # Described below
      type: kubernetes.io/basic-auth
      stringData:
        username: $(params.gitusername)
        password: $(params.gitpassword)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: git-build
      secrets:
        - name: github-token
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: git-repo-resource
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        type: git
        params:
        - name: revision
          value: $(params.gitrevision)
        - name: url
          value: $(params.gitrepositoryurl)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: shell-
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        serviceAccount: git-build
        pipelineRef:
            name: shell-pipeline
        params:
        - name: message
          value: $(params.message)
        resources:
        - name: source-repo
          resourceRef:
            name: git-repo-resource
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-pipeline-binding
spec:
  params:
    - name: gitrevision
      value: $(event.head_commit.id)
    - name: gitrepositoryurl
      value: $(event.repository.url)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-pipeline-binding
spec:
  params:
    - name: gitrevision
      value: master
    - name: gitrepositoryurl
      value: https://github.com/open-toolchain/hello-containers
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-listener
spec:
  triggers:
    - binding:
        name: manual-pipeline-binding
      template:
        name: shell-template
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: git-event-listener
spec:
  triggers:
    - binding:
        name: git-pipeline-binding
      template:
        name: shell-template