apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
  tasks:
    - name: pipeline-task
      taskRef:
        name: task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
