apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task
spec:
  steps:
    - name: echo
      image: ubuntu
      command: ["/bin/sh", "-c"]
      args:
        - echo hello;
          pwd;
          ls -la;
      
