apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the task pvc
  steps:
    - name: hello
      image: ubuntu
      command: ["/bin/sh", "-c"]
      args:
        - echo hello > /step-mount/hello
          ls -la /step-mount;
          cat /step-mount/hello;
      volumeMounts:
        - mountPath: /step-mount
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
      
