apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: shell-pipeline
spec:
  params:
    - name: message
      default: default pipeline message
  tasks:
    - name: shell-with-a-task
      taskRef:
        name: shell-task
