apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: shell-task
spec:
  steps:
    - name: echo
      image: ubuntu
      command: ["/bin/sh", "-c"]
      args:
        - echo starting;
          ls -la;
          git clone;
          https://github.com/skaegi/tekton-example;
          ls -la;
      
